### ISSUE TITLE
Scan never stops

### ISSUE THREAD

**Issue by Jhonnyc** [thedamfr/Android-BleEventAdapter#1]
First of all thanks for your contribution.
I am trying to use your code in order to discover a TI CC2541 keyfob BLE device with a samsung galaxy S4 running android 4.3 but it just never stops. my code is attached below can you tell me what I am doing wrong?

package com.keyfob;

import com.squareup.otto.Subscribe;
import com.thedamfr.android.BleEventAdapter.BleEventAdapter;
import com.thedamfr.android.BleEventAdapter.BleEventBus;
import com.thedamfr.android.BleEventAdapter.events.DiscoveredDevicesEvent;
import com.thedamfr.android.BleEventAdapter.events.ScanningEvent;

import android.os.Bundle;
import android.app.Activity;
import android.bluetooth.BluetoothDevice;
import android.view.Menu;
import android.view.View;

public class MainActivity extends Activity {

```
// Class variables
BluetoothDevice device;

@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_main);
    BleEventAdapter.getInstance().startScanning(this);
}

@Override
protected void onResume() {
    super.onResume();
    BleEventBus.getInstance().register(this);
    BleEventAdapter.getInstance().startScanning(this);
}

public void ActivateAlert(View v) {

}

@Override
protected void onPause() {
    super.onPause();
    BleEventBus.getInstance().unregister(this);
}

@Subscribe
public void onDiscoveredDevice(DiscoveredDevicesEvent event) {
    device = event.getDevice();
}
```

}

**Comment by thedamfr** [comment]
That's correct. You should stop it by yourself.
Stop it in the `onDiscoveredDevice` and use a Handler to cut it off.

``` java
 mHandler.postDelayed(new Runnable() {
                @Override
                public void run() {
                    BleEventAdapter.getInstance(). closeConnection(this)
                }
            }, SCAN_PERIOD);
```

Are you suggesting as a feature that the scan should stop by itself after a certain period ? :)

**Comment by Jhonnyc** [comment]
That can defiently be nice.. =)
TNX for your response
